language: node_js
node_js:
  - "lts/*"
install:
  - pushd server
  - npm ci
  - popd
  - pushd client
  - npm ci
  - popd
cache:
  directories:
    - ~/.npm
    - ~/.cache
  stages:
    - tests

jobs:
  include:
    - stage: tests
      name: Integration
      before_script:
        - npm run start:server:test &
      script:
        - npm run test:headless