version: '3'
services:
    server:
        restart: unless-stopped
        build:
            context: './server/'
        ports:
            - 3001:3001
            - 4040:4040
        volumes:
            - ./server/database/data/:/home/amq_server/database/data
            - ./server/logs/:/home/amq_server/logs
        environment:
            - NGROK_TOKEN
        logging:
            options:
                max-size: 50m