module.exports = {
  'Suzumiya Haruhi no Yuuutsu': ['The Melancholy of Haruhi Suzumiya'],
  'Suzumiya Haruhi no Yuuutsu (2009)': ['The Melancholy of Haruhi Suzumiya (2009)'],
  'Suzumiya Haruhi no Shoushitsu': ['The Disappearance of Haruhi Suzumiya'],
  'Toaru Kagaku no Railgun': ['A Certain Scientific Railgun'],
  'Shingeki no Kyojin': ['Attack on Titan'],
  'Shingeki no Kyojin Season 2': ['Attack on Titan Season 2'],
  'Shingeki no Kyojin Season 3': ['Attack on Titan Season 3'],
  'Shingeki no Kyojin Season 3 Part 2': ['Attack on Titan Season 3 Part 2'],
  'Shokugeki no Souma: Ni no Sara': ['Food Wars! The Second Plate'],
  'Shokugeki no Souma: San no Sara': ['Food Wars! The Third Plate'],
  'Shokugeki no Souma: San no Sara - Toutsuki Ressha-hen': ['Food Wars! The Third Plate Part 2'],
  'Sakurasou no Pet na Kanojo': ['The Pet Girl of Sakurasou'],
  'Kyoukai no Kanata': ['Beyond the Boundary'],
  'Shigatsu wa Kimi no Uso': ['Your Lie in April'],
  'Mahoutsukai no Yome': ['The Ancient Magus Bride'],
  'Nagi no Asukara': ['A Lull in the Sea'],
  'Mahou Shoujo Ikusei Keikaku': ['Magical Girl Raising Project'],
  'Yuuki Yuuna wa Yuusha de Aru': ['Yuki Yuna is a Hero'],
  'Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou': ['Yuki Yuna is a Hero: The Hero Chapter'],
  'Gakkou Gurashi!': ['School-Live!'],
  'Ookami to Koushinryou': ['Spice and Wolf'],
  'Ookami to Koushinryou II': ['Spice and Wolf II'],
  'Boku dake ga Inai Machi': ['ERASED'],
  'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.': ['Anohana.'],
  'Genei wo Kakeru Taiyou': ['Day Break Illusion'],
  'Ansatsu Kyoushitsu (TV)': ['Assassination Classroom'],
  'Ansatsu Kyoushitsu (TV) 2nd Season': ['Assassination Classroom II'],
  'Ore no Nounai Sentakushi ga, Gakuen Love Comedy wo Zenryoku de Jama Shiteiru': ['Noucome'],
  'Ore no Kanojo to Osananajimi ga Shuraba Sugiru': ['Oreshura'],
  'Shuumatsu Nani Shitemasu ka? Isogashii desu ka? Sukutte Moratte Ii desu ka?': ['SukaSuka'],
  'Kanojo ga Flag wo Oraretara': ['Gaworare'],
  'Busou Shoujo Machiavellianism': ['Armed Girl\'s Machiavellism'],
  'Kono Subarashii Sekai ni Shukufuku wo! 2': ['KonoSuba II'],
  'Kono Subarashii Sekai ni Shukufuku wo!': ['KonoSuba'],
  'Mikakunin de Shinkoukei': ['Engaged to the Unidentified'],
  'Oretachi ni Tsubasa wa Nai: Under the Innocent Sky.': ['We Without Wings – Under the Innocent Sky'],
  'Rakudai Kishi no Cavalry': ['Chivalry of a Failed Knight'],
  'Rokudenashi Majutsu Koushi to Akashic Records': ['Akashic Records of Bastard Magic Instructor'],
  'ChäoS;HEAd': ['Chaos;Head'],
  'Kämpfer': ['Kampfer'],
  'Seirei Tsukai no Blade Dance': ['Blade Dance of the Elementalers'],
  'Shoujo-tachi wa Kouya wo Mezasu': ['Girls beyond the youth KOYA'],
  'Tonari no Kaibutsu-kun': ['My Little Monster'],
  'Kami nomi zo Shiru Sekai': ['The World God Only Knows'],
  'Gin no Saji 2nd Season': ['Silver Spoon II'],
  'Gin no Saji': ['Silver Spoon'],
  'Danna ga Nani wo Itteiru ka Wakaranai Ken': ['I Can\'t Understand What My Husband Is Saying'],
  'Kono Naka ni Hitori, Imouto ga Iru!': ['Nakaimo'],
  'Danshi Koukousei no Nichijou': ['Daily Lives of High School Boys'],
  'Ore no Imouto ga Konnani Kawaii Wake ga Nai.': ['Oreimo II'],
  'Ore no Imouto ga Konnani Kawaii Wake ga Nai': ['Oreimo'],
  'Ao no Exorcist': ['Blue Exorcist'],
  'Zero kara Hajimeru Mahou no Sho': ['Grimoire of Zero'],
  'Kiseijuu: Sei no Kakuritsu': ['Parasyte -the maxim-'],
  'Naruto: Shippuuden': ['Naruto Shippuuden'],
  'Maria†Holic': ['Maria Holic'],
  'Watashi ga Motenai no wa Dou Kangaetemo Omaera ga Warui!': ['WATAMOTE.'],
  'Hidan no Aria': ['Aria the Scarlet Ammo'],
  'Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai': ['Rascal Does Not Dream of Bunny Girl Senpai'],
  'Shinrei Tantei Yakumo': ['Psychic Detective Yakumo'],
  'Byousoku 5 Centimeter': ['5 Centimeters Per Second'],
  'Hachimitsu to Clover II': ['Honey and Clover II'],
  'Hachimitsu to Clover': ['Honey and Clover'],
  'Shinsekai yori': ['From the New World'],
  'Kareshi Kanojo no Jijou': ['His and Her Circumstances'],
  'Tetsuwan Atom': ['Astro Boy'],
  'Danna ga Nani wo Itteiru ka Wakaranai Ken 2 Sure-me': ['I Can\'t Understand What My Husband Is Saying: 2nd Thread'],
  'The King\'s Avatar': ['Quan Zhi Gao Shou'],
  'Code Geass: Hangyaku no Lelouch R2': ['Code Geass: Lelouch of the Rebellion R2'],
  'Code Geass: Hangyaku no Lelouch': ['Code Geass: Lelouch of the Rebellion'],
  'Mahou Shoujo Madoka★Magica': ['Puella Magi Madoka★Magica']
}