module.exports = {
  'Raison D’être': 'Raison D\'être',
  'Black★Rock Shooter': 'Black Rock Shooter',
  'Zenryoku☆Summer!': 'Zenryoku Summer!',
  'Onegai☆Snyaiper': 'Onegai Snyaiper',
  'Cordless☆Dere☆PHONE': 'Cordless Dere PHONE',
  'S・M・L☆': 'SML☆',
  'Witch☆Activity': 'Witch Activity',
  'Fly Me to the Moon (Aki Jungle Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon (Aya Bossa Techno Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon (Off-Vocal Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon (Rei #23 Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon (Rei #25 Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon (Rei #26 Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon (Rei #5 Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon (Rei #6 Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon (Yoko Takahashi Acid Bossa Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon (Yoko Takahashi Version)': 'Fly Me to the Moon',
  'Fly Me to the Moon -4 Beat Version (Off-Vocal)-': 'Fly Me to the Moon',
  'Fly Me to the Moon -4 Beat Version-': 'Fly Me to the Moon',
  'Fly Me to the Moon -B22 (A-Type)-': 'Fly Me to the Moon',
  'Hello!My World!!': 'Hello! My World!!'
}