module.exports = {
  'Suzumiya Haruhi no Yuuutsu': ['The Melancholy of Haruhi Suzumiya'],
  'Suzumiya Haruhi no Yuuutsu (2009)': ['The Melancholy of Haruhi Suzumiya (2009)'],
  'Suzumiya Haruhi no Shoushitsu': ['The Disappearance of Haruhi Suzumiya'],
  'Toaru Kagaku no Railgun': ['A Certain Scientific Railgun'],
  'Shingeki no Kyojin': ['Attack on Titan'],
  'Shingeki no Kyojin Season 2': ['Attack on Titan Season 2'],
  'Shingeki no Kyojin Season 3': ['Attack on Titan Season 3'],
  'Shingeki no Kyojin Season 3 Part 2': ['Attack on Titan Season 3 Part 2'],
  'Shokugeki no Souma: Ni no Sara': ['Food Wars! The Second Plate'],
  'Shokugeki no Souma: San no Sara': ['Food Wars! The Third Plate'],
  'Shokugeki no Souma: San no Sara - Toutsuki Ressha-hen': ['Food Wars! The Third Plate Part 2'],
  'Sakurasou no Pet na Kanojo': ['The Pet Girl of Sakurasou'],
  'Kyoukai no Kanata': ['Beyond the Boundary'],
  'Shigatsu wa Kimi no Uso': ['Your Lie in April'],
  'Mahoutsukai no Yome': ['The Ancient Magus Bride'],
  'Nagi no Asukara': ['A Lull in the Sea'],
  'Mahou Shoujo Ikusei Keikaku': ['Magical Girl Raising Project'],
  'Yuuki Yuuna wa Yuusha de Aru': ['Yuuki Yuuna is a Hero'],
  'Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou': ['Yuuki Yuuna is a Hero: The Hero Chapter'],
  'Gakkou Gurashi!': ['School-Live!'],
  'Ookami to Koushinryou': ['Spice and Wolf'],
  'Ookami to Koushinryou II': ['Spice and Wolf II'],
  'Boku dake ga Inai Machi': ['ERASED'],
  'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.': ['Anohana.'],
  'Genei wo Kakeru Taiyou': ['Day Break Illusion'],
  'Ansatsu Kyoushitsu (TV)': ['Assassination Classroom'],
  'Ansatsu Kyoushitsu (TV) 2nd Season': ['Assassination Classroom II']
}